/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2018-04-09 04:07:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge; charset=UTF-8\">\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> \n");
      out.write("\t\t<title>Registro Alumnos</title>\n");
      out.write("\t\t<meta name=\"description\" content=\"Formulario de registro de nuevos alumnos\" />\n");
      out.write("\t\t<meta name=\"keywords\" content=\"registro, alumnos, nuevos, cetech\" />\n");
      out.write("\t\t<meta name=\"author\" content=\"Cetech\" />\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"../favicon.ico\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/normalize.css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/demo.css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/component.css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/cs-select.css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/cs-skin-boxes.css\" />\n");
      out.write("\t\t<script src=\"js/modernizr.custom.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"fs-form-wrap\" id=\"fs-form-wrap\">\n");
      out.write("\t\t\t\t<div class=\"fs-title\">\n");
      out.write("\t\t\t\t\t<h1>CETECH - REGISTRO de ALUMNOS</h1>\n");
      out.write("\t\t\t\t\t     ");

	if(request.getAttribute("correcto")!=null && request.getAttribute("correcto").equals("Si"))
	{
		
      out.write("\n");
      out.write("<!-- \t\t<div class=\"divAlertaCorrecto\"> -->\n");
      out.write("\t\t\t<h1>");
      out.print(request.getAttribute("mensajeGeneral"));
      out.write("</h1>\n");
      out.write("<!-- \t\t</div> -->\n");
      out.write("\t\t");

	}
	if(request.getAttribute("correcto")!=null && request.getAttribute("correcto").equals("No"))
	{
		
      out.write("\n");
      out.write("<!-- \t\t<div class=\"divAlertaError\"> -->\n");
      out.write("\t\t\t<h1>");
      out.print(request.getAttribute("mensajeGeneral"));
      out.write("</h1>\n");
      out.write("<!-- \t\t</div> -->\n");
      out.write("\t\t");

	}
	
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"codrops-top\">\n");
      out.write("\t\t\t\t\t\t<a class=\"codrops-icon codrops-icon-prev\" href=\"#\"><span>Anterior</span></a>\n");
      out.write("\t\t\t\t\t\t<a class=\"codrops-icon codrops-icon-drop\" href=\"http://cetech.com.mx\"><span>Ir a Cetech</span></a>\n");
      out.write("\t\t\t\t\t\t<a class=\"codrops-icon codrops-icon-info\" href=\"#\"><span>Toda esta informacion es confidencial</span></a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<form action=\"validandoFormulario\" method=\"post\" id=\"myform\" class=\"fs-form fs-form-full\" autocomplete=\"off\">\n");
      out.write("\t\t\t\t\t<ol class=\"fs-fields\">\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"nombre\">Nombre</label>\n");
      out.write("\t\t\t\t\t\t\t<input class=\"fs-anim-lower\" id=\"nombre\" name=\"nombre\" type=\"text\" placeholder=\"Solo Tu Nombre!\" required/>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"paterno\">Apellido Paterno</label>\n");
      out.write("\t\t\t\t\t\t\t<input class=\"fs-anim-lower\" id=\"paterno\" name=\"paterno\" type=\"text\" placeholder=\"Sanchez\" required/>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"materno\">Apellido Materno</label>\n");
      out.write("\t\t\t\t\t\t\t<input class=\"fs-anim-lower\" id=\"materno\" name=\"materno\" type=\"text\" placeholder=\"Cruz\" required/>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"correo\" data-info=\"Se enviara informacion importante a esta direccion\">E-mail?</label>\n");
      out.write("\t\t\t\t\t\t\t<input class=\"fs-anim-lower\" id=\"correo\" name=\"correo\" type=\"email\" placeholder=\"usuario@dominio.com\" required/>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<!-- <li data-input-trigger>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"curso\">Tu curso es (Seleccionalo): </label>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fs-radio-group fs-radio-custom clearfix fs-anim-lower\">\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"cursob\" name=\"curso\" type=\"radio\" value=\"JavaBasico(JSE)\"/><label for=\"curso\" class=\"radio-conversion\">Java Basico(JSE)</label></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"cursoc\" name=\"curso\" type=\"radio\" value=\"JavaWeb(JEE)\"/><label for=\"curso\" class=\"radio-social\">Java Web (JEE)</label></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"cursob\" name=\"curso\" type=\"radio\" value=\"BasedeDatosOracle(Basico)\"/><label for=\"curso\" class=\"radio-conversion\">Base de Datos Oracle(Basico)</label></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"cursoc\" name=\"curso\" type=\"radio\" value=\".NET\"/><label for=\"curso\" class=\"radio-social\">.NET</label></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"cursoa\" name=\"curso\" type=\"radio\" value=\"Android\"/><label for=\"curso\" class=\"radio-mobile\">Android</label></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</li>  se agrego como comentario porqué dicho código no respondia al darle click a los cursos-->\n");
      out.write("\t\t\t\t\t\t<li data-input-trigger>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"curso\" data-info=\"Tú curso es: \">Tu curso es:</label>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fs-radio-group fs-radio-custom clearfix fs-anim-lower\">\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"cursoA\" name=\"curso\" type=\"radio\" value=\"Java Basico JSE\"/><label for=\"cursoA\" class=\"radio-conversion\">Java Basico JSE</label></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"cursoB\" name=\"curso\" type=\"radio\" value=\"Java web JEE\"/><label for=\"cursoB\" class=\"radio-social\">Java Web JEE</label></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"cursoC\" name=\"curso\" type=\"radio\" value=\"Android Basico\"/><label for=\"cursoC\" class=\"radio-mobile\">Android Basico</label></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"cursoD\" name=\"curso\" type=\"radio\" value=\"Oracle Basico\"/><label for=\"cursoD\" class=\"radio-conversion\">Oracle Basico</label></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li data-input-trigger>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"formaDePago\" data-info=\"Tú curso es: \">Forma de pago:</label>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fs-radio-group fs-radio-custom clearfix fs-anim-lower\">\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"formaDePagoA\" name=\"formaDePago\" type=\"radio\" value=\"Mensual\"/><label for=\"formaDePagoA\" class=\"radio-conversion\">Mensual</label></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"formaDePagoB\" name=\"formaDePago\" type=\"radio\" value=\"Semanal\"/><label for=\"formaDePagoB\" class=\"radio-social\">Semanal</label></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"formaDePagoC\" name=\"formaDePago\" type=\"radio\" value=\"SolaExhibicion\"/><label for=\"formaDePagoC\" class=\"radio-mobile\">Una Sola Exhibicón</label></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<li data-input-trigger>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" >Escoje un color para tu sexo.</label>\n");
      out.write("\t\t\t\t\t\t\t<select name=\"miCombo\" class=\"cs-select cs-skin-boxes fs-anim-lower\">\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\" disabled selected>Pick a color</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"#588c75\" data-class=\"color-588c75\">Hombre</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"#f7cda9\" data-class=\"color-f7cda9\">Mujer</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("<!-- \t\t\t\t\t\t<li data-input-trigger> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"sexo\" data-info=\"This will help us know what kind of service you need\">Cual es tu sexo?</label> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t<div class=\"fs-radio-group fs-radio-custom clearfix fs-anim-lower\"> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<span><input id=\"sexob\" name=\"sexo\" type=\"radio\" value=\"true\"/><label for=\"sexo\" class=\"radio-conversion\">Hombre</label></span> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<span><input id=\"sexoc\" name=\"sexo\" type=\"radio\" value=\"false\"/><label for=\"sexo\" class=\"radio-social\">Mujer</label></span> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<span><input id=\"sexoa\" name=\"sexo\" type=\"radio\" value=\"true\"/><label for=\"sexo\" class=\"radio-mobile\">Indefinido</label></span> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t</div> -->\n");
      out.write("<!-- \t\t\t\t\t\t</li> -->\t\t\t\t\n");
      out.write("<!-- \t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"edad\">Cual es tu edad</label>\n");
      out.write("\t\t\t\t\t\t\t<input class=\"fs-mark fs-anim-lower\" id=\"edad\" name=\"edad\" type=\"number\" placeholder=\"20\" step=\"1\" min=\"14\"/>\n");
      out.write("\t\t\t\t\t\t</li> Se pone comentario para no borrar esta parte de codigo y no eliminarla,la edad las sacaremos con la fecha de nacimiento\n");
      out.write("\t\t\t\t\t\t\tpero no se hará en este momento aún.--> \n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"fechaNacimiento\" >Fecha de Nacimiento</label>\n");
      out.write("\t\t\t\t\t\t\t<input class=\"fs-anim-lower\" id=\"fechaNacimiento\" name=\"fechaNacimiento\" type=\"date\" placeholder=\"2015/11/29\" required/>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"celular\" data-info=\"Se agregara al grupo de WhatsApp\">Numero De Tu Celular</label>\n");
      out.write("\t\t\t\t\t\t\t<input class=\"fs-anim-lower\" id=\"celular\" name=\"celular\" type=\"tel\" placeholder=\"5511223344\"  maxlength=\"10\" pattern=\"[0-9]{10}\" required/>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<!-- aquí va el domicilio -->\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"calle\">Domicilio/Calle #</label>\n");
      out.write("\t\t\t\t\t\t\t<input class=\"fs-anim-lower\" id=\"calle\" name=\"calle\" type=\"text\" placeholder=\"Vallarta 7\" required/>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"codigoPostal\" data-info=\"\">Codigo Postal</label>\n");
      out.write("\t\t\t\t\t\t\t<input class=\"fs-anim-lower\" id=\"codigoPostal\" name=\"codigoPostal\" type=\"text\" placeholder=\"06030\"  maxlength=\"5\" pattern=\"[0-9]{5}\" required/>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"colonia\">Colonia</label>\n");
      out.write("\t\t\t\t\t\t\t<input class=\"fs-anim-lower\" id=\"colonia\" name=\"colonia\" type=\"text\" placeholder=\"Tabacalera\" required/>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"estado\">Estado</label>\n");
      out.write("\t\t\t\t\t\t\t<input class=\"fs-anim-lower\" id=\"estado\" name=\"estado\" type=\"text\" placeholder=\"CDMX\" required/>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write(" \t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"delegacion\">Delegacion</label>\n");
      out.write("\t\t\t\t\t\t\t<input class=\"fs-anim-lower\" id=\"delegacion\" name=\"delegacion\" type=\"text\" placeholder=\"delegacion\" required/>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write(" \t\t\t\t\t\t<li> \n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"Ocupacion\">Ocupacion</label> \n");
      out.write(" \t\t\t\t\t\t\t<input class=\"fs-anim-lower\" id=\"ocupacion\" name=\"ocupacion\" type=\"text\" placeholder=\"ocupacion\" required/> \n");
      out.write(" \t\t\t\t\t\t</li> \n");
      out.write("\t\t\t\t\t\t<li data-input-trigger>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\">Tu Nivel Academico.</label>\n");
      out.write("\t\t\t\t\t\t\t<select name=\"miCombo2\" class=\"cs-select cs-skin-boxes fs-anim-lower\">\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\" disabled selected>Pick a color</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"#588c75\" data-class=\"color-588c75\">Formación básica (primaria)</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"#b0c47f\" data-class=\"color-b0c47f\">media (secundaria)</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"#f3e395\" data-class=\"color-f3e395\">media superior (preparatoria)</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"#f3ae73\" data-class=\"color-f3ae73\">superior (universidad)</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"#da645a\" data-class=\"color-da645a\">pos grado (maestría y doctorado)</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"escuela\">Cual Es Tu Escuela.</label>\n");
      out.write("\t\t\t\t\t\t\t<input class=\"fs-anim-lower\" id=\"escuela\" name=\"escuela\" type=\"text\" placeholder=\"CETECH\" required/>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li data-input-trigger>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"q3\" data-info=\"Como te enteraste de nosotros\">Como te enteraste</label>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fs-radio-group fs-radio-custom clearfix fs-anim-lower\">\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"q3a\" name=\"q3\" type=\"radio\" value=\"recomecacion\"/><label for=\"q3a\" class=\"radio-conversion\">Recomendacion</label></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"q3b\" name=\"q3\" type=\"radio\" value=\"social\"/><label for=\"q3b\" class=\"radio-social\">Redes Sociales</label></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"q3c\" name=\"q3\" type=\"radio\" value=\"mobile\"/><label for=\"q3c\" class=\"radio-mobile\">Publicidad Impresa</label></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"expectativas\">Para que tomas el curso</label>\n");
      out.write("\t\t\t\t\t\t\t<textarea class=\"fs-anim-lower\" id=\"expectativas\" name=\"expectativas\" placeholder=\"Describe aqui\"></textarea>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<!-- <li>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"recomendacion\">Nos recomendarías con alguna persona,familiar u amigo.</label>\n");
      out.write("\t\t\t\t\t\t\t<input class=\"fs-anim-lower\" id=\"recomendacion\" name=\"recomendacion\" type=\"text\" placeholder=\"si,no.\" required/>\n");
      out.write("\t\t\t\t\t\t</li> -->\n");
      out.write("\t\t\t\t\t<!-- \t<li data-input-trigger>\n");
      out.write("\t\t\t\t\t\t\t<label class=\"fs-field-label fs-anim-upper\" for=\"curso\">Que otro curso tomarias</label>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fs-radio-group fs-radio-custom clearfix fs-anim-lower\">\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"cursob\" name=\"otroCurso\" type=\"radio\" value=\"java\"/><label for=\"curso\" class=\"radio-conversion\">Java Básico</label></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"cursob\" name=\"otroCurso\" type=\"radio\" value=\"android\"/><label for=\"curso\" class=\"radio-conversion\">Base de Datos (Oracle Básico)</label></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"cursob\" name=\"otroCurso\" type=\"radio\" value=\"bootstrap\"/><label for=\"curso\" class=\"radio-conversion\">.NET(Básico)</label></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span><input id=\"cursoa\" name=\"otroCurso\" type=\"radio\" value=\"otro\"/><label for=\"curso\" class=\"radio-mobile\">Otro</label></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</li> --> \n");
      out.write("\t\t\t\t\t</ol><!-- /fs-fields -->\n");
      out.write("\t\t\t\t\t<button class=\"fs-submit\" type=\"submit\">Enviar Registro</button>\n");
      out.write("\t\t\t\t</form><!-- /fs-form -->\n");
      out.write("\t\t\t</div><!-- /fs-form-wrap -->\n");
      out.write("\n");
      out.write("\t\t\t<!-- Related demos -->\n");
      out.write("\t\t\t<div class=\"related\">\n");
      out.write("\t\t\t\t<p>Otros Registros:</p>\n");
      out.write("\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t<img src=\"img/relatedposts/minimalform1-300x162.png\" />\n");
      out.write("\t\t\t\t\t<h3>Visitas</h3>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t<img src=\"img/relatedposts/MorphingButtons-300x162.png\" />\n");
      out.write("\t\t\t\t\t<h3>Administracion</h3>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div><!-- /container -->\n");
      out.write("\t\t<script src=\"js/classie.js\"></script>\n");
      out.write("\t\t<script src=\"js/selectFx.js\"></script>\n");
      out.write("\t\t<script src=\"js/fullscreenForm.js\"></script>\n");
      out.write("\t\t<script>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t(function() {\n");
      out.write("\t\t\t\tvar formWrap = document.getElementById( 'fs-form-wrap' );\n");
      out.write("\n");
      out.write("\t\t\t\t[].slice.call( document.querySelectorAll( 'select.cs-select' ) ).forEach( function(el) {\t\n");
      out.write("\t\t\t\t\tnew SelectFx( el, {\n");
      out.write("\t\t\t\t\t\tstickyPlaceholder: false,\n");
      out.write("\t\t\t\t\t\tonChange: function(val){\n");
      out.write("\t\t\t\t\t\t\tdocument.querySelector('span.cs-placeholder').style.backgroundColor = val;\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t} );\n");
      out.write("\n");
      out.write("\t\t\t\tnew FForm( formWrap, {\n");
      out.write("\t\t\t\t\tonReview : function() {\n");
      out.write("\t\t\t\t\t\tclassie.add( document.body, 'overview' ); // for demo purposes only\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t} );\n");
      out.write("\t\t\t})();\n");
      out.write("\t\t</script>\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t$(document).ready(function() {\n");
      out.write("\t\t    // Así accedemos al Valor de la opción seleccionada\n");
      out.write("\t\t    var valor = $(\"#miCombo\").val();\n");
      out.write("\t\t    alert(valor);\n");
      out.write("\t\t    // Si seleccionamos la opción \"Texto 1\"\n");
      out.write("\t\t    // nos mostrará por pantalla \"1\"\n");
      out.write("\t\t});\n");
      out.write("\t\t</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
